//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalReportDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inv_UserSecurities
    {
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public int InvalidLogins { get; set; }
        public bool Locked { get; set; }
        public string SessionId { get; set; }
        public bool Active { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string PasswordChangedBy { get; set; }
        public bool IsSupplier { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
        public string Address { get; set; }
        public bool IsLogin { get; set; }
        public System.DateTime LastLogin { get; set; }
        public string SecurityQuestion { get; set; }
        public string SecurityAnswer { get; set; }
        public string Last_password1 { get; set; }
        public string Last_password2 { get; set; }
        public string Last_password3 { get; set; }
        public Nullable<bool> Force_change_password { get; set; }
        public Nullable<System.DateTime> PasswordUpdate { get; set; }
        public string PasswordCounter { get; set; }
        public string TemperNumber { get; set; }
        public string TemperUrl { get; set; }
        public Nullable<bool> IsEloActiveUser { get; set; }
        public string DocumentName { get; set; }
        public string DocumentUrl { get; set; }
        public Nullable<System.DateTime> InActiveDate { get; set; }
        public Nullable<System.DateTime> ReActiveDate { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> UserSecurityImageId { get; set; }
        public bool DohUsers { get; set; }
        public bool TopwaReport { get; set; }
        public bool IsLoginBypass { get; set; }
        public string UserClaimsObjectId { get; set; }
        public Nullable<int> ActiveNotice { get; set; }
        public bool IsInviteSent { get; set; }
        public bool IsDeleted { get; set; }
    }
}
